### ISSUE TITLE
Can't run openrndr-gradle-template program

### ISSUE THREAD

**Issue by alexdmiller** [openrndr/openrndr#11]
**Describe the bug**
I followed the tutorial [here](http://guide.openrndr.org/#/Tutorial_Start), but I get an error (pasted below).

**To Reproduce**
Follow the steps as outlined in the OPENRNDR getting started guide and run the template program.

**Expected behavior**
I would expect the template program to run.

**Screenshots**
<img width="1067" alt="screen shot 2018-07-10 at 12 20 19 pm" src="https://user-images.githubusercontent.com/926408/42532426-bab06b20-843b-11e8-9d50-73c18f801a9f.png">

**Context:**
 - OS and version: macOS 10.11.6
 - OpenRNDR version: 0.3.18
 - Java Version: 1.8.0_05

**Additional context**

Logs:

```
objc[14792]: Class JavaLaunchHelper is implemented in both /Library/Java/JavaVirtualMachines/jdk1.8.0_05.jdk/Contents/Home/bin/java and /Library/Java/JavaVirtualMachines/jdk1.8.0_05.jdk/Contents/Home/jre/lib/libinstrument.dylib. One of the two will be used. Which one is undefined.
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
3.3.0 Cocoa NSGL dynamic
opengl vendor: ATI Technologies Inc.
opengl version: 4.1 ATI-1.42.15
java.lang.VerifyError: Uninitialized object exists on backward branch 43
Exception Details:
  Location:
    org/openrndr/shape/ShapeContour.getReversed()Lorg/openrndr/shape/ShapeContour; @89: goto
  Reason:
    Error exists in the bytecode
  Bytecode:
    0000000: bb00 0259 2ab4 000a c000 0c4c 3a0b 3a0a
    0000010: 2b4d bb00 3459 2b10 0ab8 008b b700 8ec0
    0000020: 003a 4e2c b900 1001 003a 0419 04b9 0016
    0000030: 0100 9900 2a19 04b9 001a 0100 3a05 2d19
    0000040: 05c0 001c 3a06 3a0c 1906 b601 8e3a 0d19
    0000050: 0c19 0db9 0098 0200 57a7 ffd2 2dc0 004f
    0000060: 3a0c 190a 190b 190c c000 0cb8 0192 2ab4
    0000070: 00f6 b700 94b0                         
  Stackmap Table:
    full_frame(@43,{Object[#2],Object[#12],Object[#12],Object[#58],Object[#18],Top,Top,Top,Top,Top,Uninitialized[#0],Uninitialized[#0]},{})
    same_frame(@92)

	at org.openrndr.shape.ShapeBuilderKt.contour(ShapeBuilder.kt:25)
	at TemplateProgram.draw(TemplateProgram.kt:12)
	at org.openrndr.Program.drawImpl(Program.kt:306)
	at org.openrndr.internal.gl3.ApplicationGL3.drawFrame(ApplicationGL3.kt:489)
	at org.openrndr.internal.gl3.ApplicationGL3.loop(ApplicationGL3.kt:436)
	at org.openrndr.Application$Companion.run(Application.kt:13)
	at org.openrndr.ApplicationKt.application(Application.kt:39)
	at TemplateProgramKt.main(TemplateProgram.kt:23)
Exception in thread "main" java.lang.VerifyError: Uninitialized object exists on backward branch 43
Exception Details:
  Location:
    org/openrndr/shape/ShapeContour.getReversed()Lorg/openrndr/shape/ShapeContour; @89: goto
  Reason:
    Error exists in the bytecode
  Bytecode:
    0000000: bb00 0259 2ab4 000a c000 0c4c 3a0b 3a0a
    0000010: 2b4d bb00 3459 2b10 0ab8 008b b700 8ec0
    0000020: 003a 4e2c b900 1001 003a 0419 04b9 0016
    0000030: 0100 9900 2a19 04b9 001a 0100 3a05 2d19
    0000040: 05c0 001c 3a06 3a0c 1906 b601 8e3a 0d19
    0000050: 0c19 0db9 0098 0200 57a7 ffd2 2dc0 004f
    0000060: 3a0c 190a 190b 190c c000 0cb8 0192 2ab4
    0000070: 00f6 b700 94b0                         
  Stackmap Table:
    full_frame(@43,{Object[#2],Object[#12],Object[#12],Object[#58],Object[#18],Top,Top,Top,Top,Top,Uninitialized[#0],Uninitialized[#0]},{})
    same_frame(@92)

	at org.openrndr.shape.ShapeBuilderKt.contour(ShapeBuilder.kt:25)
	at TemplateProgram.draw(TemplateProgram.kt:12)
	at org.openrndr.Program.drawImpl(Program.kt:306)
	at org.openrndr.internal.gl3.ApplicationGL3.drawFrame(ApplicationGL3.kt:489)
	at org.openrndr.internal.gl3.ApplicationGL3.loop(ApplicationGL3.kt:436)
	at org.openrndr.Application$Companion.run(Application.kt:13)
	at org.openrndr.ApplicationKt.application(Application.kt:39)
	at TemplateProgramKt.main(TemplateProgram.kt:23)
```

**Comment by edwinRNDR** [comment]
Interesting. Would you be able to test this with a new version of Java 8? this particular version (1.8.0_05) seems to be from 2014.

**Comment by alexdmiller** [comment]
Thanks for the quick response. Changing the Java version worked.

For future reference, I had to change the JRE version in the Run configuration window:

<img width="887" alt="screen shot 2018-07-10 at 4 22 02 pm" src="https://user-images.githubusercontent.com/926408/42542833-806a6246-845d-11e8-878a-a86cd525b502.png">
