### ISSUE TITLE
App with resizable window crashes when minimized on Windows

### ISSUE THREAD

**Issue by shi-weili** [openrndr/openrndr#218]
**Describe the bug**
If configured with `windowResizable = true`, the app will crash on Windows 10 when the window is minimized.

**To Reproduce**
In `application { configure {} }`, add `windowResizable = true`. Build and run the app, then click the minimize button of the app window.

**Expected behavior**
The app crashes with console output similar to the following:

```
ERROR [main] o.o.e.Event                     ↘ Exception thrown in listener ('window-sized'): IllegalArgumentException; 'unsupported resolution (0×0)'
Exception in thread "main" java.lang.IllegalArgumentException: unsupported resolution (0×0)
	at org.openrndr.draw.RenderTargetKt.renderTarget(RenderTarget.kt:233)
	at org.openrndr.draw.RenderTargetKt.renderTarget$default(RenderTarget.kt:230)
	at org.openrndr.panel.ControlManager.resize(ControlManager.kt:376)
	at org.openrndr.panel.ControlManager.access$resize(ControlManager.kt:72)
	at org.openrndr.panel.ControlManager$setup$11.invoke(ControlManager.kt:346)
	at org.openrndr.panel.ControlManager$setup$11.invoke(ControlManager.kt:72)
	at org.openrndr.events.Event.deliver(Event.kt:132)
	at org.openrndr.internal.gl3.ApplicationGLFWGL3.deliverEvents(ApplicationGLFWGL3.kt:704)
	at org.openrndr.internal.gl3.ApplicationGLFWGL3.drawFrame(ApplicationGLFWGL3.kt:727)
	at org.openrndr.internal.gl3.ApplicationGLFWGL3.loop(ApplicationGLFWGL3.kt:655)
	at org.openrndr.Application$Companion.run(Application.kt:46)
	at org.openrndr.ApplicationKt.application(Application.kt:97)
	at org.openrndr.ApplicationBuilderKt.application(ApplicationBuilder.kt:109)
	at CCAAppKt.main(CCAApp.kt:17)
	at CCAAppKt.main(CCAApp.kt)
```

**Context:**
 - OS and version: Windows 10 Pro 19041.867
 - OpenRNDR version: 0.3.44
 - Java Version: openjdk-15.0.2

**Additional context**
The app responds to window resizing correctly. It also doesn't crash when minimized on macOS.

**Comment by shi-weili** [comment]
Sorry, what's causing the app to crash is not `windowResizable`, but `orx-gui`. I'm closing this issue and opening a new one in the `orx` repo.
