### ISSUE TITLE
Creating a ShapeContour .offset() may produce a first segment with NaN value

### ISSUE THREAD

**Issue by hamoid** [openrndr/openrndr#79]
**Describe the bug**
Calling .offset() on a ShapeContour produces an invalid curve in some cases

**To Reproduce**
```
    program {

        val curve = contour {
            moveTo(Vector2(0.1 * width, 0.3 * height))
            continueTo(Vector2(0.5 * width, 0.5 * height))
            continueTo(Vector2(0.9 * width, 0.3 * height))
            continueTo(Vector2(0.1 * width, 0.3 * height))
            close()
        }

        val curve2 = curve.offset(20.0, SegmentJoin.ROUND)

        println(curve2.segments[0])
        println(curve2.segments[1])
        println(curve2.segments[curve2.segments.size-2])
        println(curve2.segments[curve2.segments.size-1])

        extend {
            drawer.contour(curve)
            drawer.contour(curve2) // <-- crash

            drawer.fill = null
            drawer.rectangle(curve.bounds)
            drawer.rectangle(curve2.bounds)
        }
    }
```
**Expected behavior**
Drawing two offset curves.

**Output**
```
Segment(start=Vector2(x=NaN, y=NaN), end=Vector2(x=111.05572809000084, y=227.88854381999832), control=[Vector2(x=NaN, y=NaN), Vector2(x=NaN, y=NaN)])
Segment(start=Vector2(x=111.05572809000084, y=227.88854381999832), end=Vector2(x=291.05572809000085, y=317.8885438199983), control=[Vector2(x=168.94427190999915, y=212.11145618000168), Vector2(x=228.94427190999915, y=242.11145618000168)])
Segment(start=Vector2(x=55.87973916815717, y=159.7054959036708), end=Vector2(x=53.47067495099499, y=160.90549399722113), control=[Vector2(x=55.07772582253885, y=160.10448872737393), Vector2(x=54.2747044156394, y=160.50448808867085)])
Segment(start=Vector2(x=53.47067495099499, y=160.90549399722113), end=Vector2(x=51.05572809000071, y=162.11145618000174), control=[Vector2(x=52.66670065119528, y=161.30647490590087), Vector2(x=51.86171836303135, y=161.70846229698998)])
```

**Context:**
 - OS and version: ArchLinux
 - OpenRNDR version 0.4.0
 - Java Version 11

**Comment by edwinRNDR** [comment]
Part of the issue is that the code for the `continueTo` command uses `cursor` as the control point when it is the first command in the contour. This results in `Segment.derivative(0.0)`  to evaluate to `Vector2(0.0, 0.0)`, which becomes `Vector2(NaN, NaN)` after normalization.

**Comment by edwinRNDR** [comment]
Addressed this in https://github.com/openrndr/openrndr/commit/d9f30307abd8cb15af0d31a5345c20fd3b34f23c 

Should be a lot better now, keeping this open until finish testing with more complex cases

**Comment by hamoid** [comment]
I tried the fix. This program
https://github.com/hamoid/openrndr-template/blob/master/src/main/kotlin/EditableCurveSketch.kt
was running fine before the change. Now sometimes (but not always) when I click Add Curve I get this error:
```
io.reactivex.exceptions.OnErrorNotImplementedException: L end/start overlap Vector2(x=640.3497753421032, y=437.05552212996145) Vector2(x=640.3497753421032, y=437.05552212996145)
	at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:704)
	at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:701)
	at io.reactivex.internal.observers.LambdaObserver.onError(LambdaObserver.java:77)
	at io.reactivex.internal.observers.LambdaObserver.onNext(LambdaObserver.java:67)
	at io.reactivex.subjects.PublishSubject$PublishDisposable.onNext(PublishSubject.java:309)
	at io.reactivex.subjects.PublishSubject.onNext(PublishSubject.java:229)
	at org.openrndr.panel.elements.Button$2.accept(Button.kt:31)
	at org.openrndr.panel.elements.Button$2.accept(Button.kt:13)
	at io.reactivex.internal.observers.LambdaObserver.onNext(LambdaObserver.java:63)
	at io.reactivex.subjects.PublishSubject$PublishDisposable.onNext(PublishSubject.java:309)
	at io.reactivex.subjects.PublishSubject.onNext(PublishSubject.java:229)
	at org.openrndr.panel.ControlManager$MouseInput.click(ControlManager.kt:192)
	at org.openrndr.panel.ControlManager$setup$1.invoke(ControlManager.kt:300)
	at org.openrndr.panel.ControlManager$setup$1.invoke(ControlManager.kt:71)
	at org.openrndr.events.Event.deliver(Event.kt:112)
	at org.openrndr.internal.gl3.ApplicationGLFWGL3.deliverEvents(ApplicationGLFWGL3.kt:676)
	at org.openrndr.internal.gl3.ApplicationGLFWGL3.drawFrame(ApplicationGLFWGL3.kt:687)
	at org.openrndr.internal.gl3.ApplicationGLFWGL3.loop(ApplicationGLFWGL3.kt:620)
	at org.openrndr.Application$Companion.run(Application.kt:33)
	at org.openrndr.ApplicationKt.application(Application.kt:76)
	at org.openrndr.ApplicationBuilderKt.application(ApplicationBuilder.kt:108)
	at EditableCurveSketchKt.main(EditableCurveSketch.kt:23)
	at EditableCurveSketchKt.main(EditableCurveSketch.kt)
Caused by: java.lang.IllegalArgumentException: L end/start overlap Vector2(x=640.3497753421032, y=437.05552212996145) Vector2(x=640.3497753421032, y=437.05552212996145)
	at org.openrndr.shape.Segment.<init>(Shape.kt:43)
	at org.openrndr.shape.ShapeContour.sampleEquidistant(Shape.kt:801)
	at EditableCurve.update(EditableCurve.kt:36)
	at EditableCurve.randomize(EditableCurve.kt:57)
	at EditableCurveSketchKt$main$1$2$3.invoke(EditableCurveSketch.kt:74)
	at EditableCurveSketchKt$main$1$2$4$3$1$1.invoke(EditableCurveSketch.kt:92)
	at EditableCurveSketchKt$main$1$2$4$3$1$1.invoke(EditableCurveSketch.kt)
	at org.openrndr.panel.elements.LayoutBuilderKt$sam$io_reactivex_functions_Consumer$0.accept(LayoutBuilder.kt)
	at io.reactivex.internal.observers.LambdaObserver.onNext(LambdaObserver.java:63)
	... 19 more
Exception in thread "main" io.reactivex.exceptions.OnErrorNotImplementedException: L end/start overlap Vector2(x=640.3497753421032, y=437.05552212996145) Vector2(x=640.3497753421032, y=437.05552212996145)
	at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:704)
	at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:701)
	at io.reactivex.internal.observers.LambdaObserver.onError(LambdaObserver.java:77)
	at io.reactivex.internal.observers.LambdaObserver.onNext(LambdaObserver.java:67)
	at io.reactivex.subjects.PublishSubject$PublishDisposable.onNext(PublishSubject.java:309)
	at io.reactivex.subjects.PublishSubject.onNext(PublishSubject.java:229)
	at org.openrndr.panel.elements.Button$2.accept(Button.kt:31)
	at org.openrndr.panel.elements.Button$2.accept(Button.kt:13)
	at io.reactivex.internal.observers.LambdaObserver.onNext(LambdaObserver.java:63)
	at io.reactivex.subjects.PublishSubject$PublishDisposable.onNext(PublishSubject.java:309)
	at io.reactivex.subjects.PublishSubject.onNext(PublishSubject.java:229)
	at org.openrndr.panel.ControlManager$MouseInput.click(ControlManager.kt:192)
	at org.openrndr.panel.ControlManager$setup$1.invoke(ControlManager.kt:300)
	at org.openrndr.panel.ControlManager$setup$1.invoke(ControlManager.kt:71)
	at org.openrndr.events.Event.deliver(Event.kt:112)
	at org.openrndr.internal.gl3.ApplicationGLFWGL3.deliverEvents(ApplicationGLFWGL3.kt:676)
	at org.openrndr.internal.gl3.ApplicationGLFWGL3.drawFrame(ApplicationGLFWGL3.kt:687)
	at org.openrndr.internal.gl3.ApplicationGLFWGL3.loop(ApplicationGLFWGL3.kt:620)
	at org.openrndr.Application$Companion.run(Application.kt:33)
	at org.openrndr.ApplicationKt.application(Application.kt:76)
	at org.openrndr.ApplicationBuilderKt.application(ApplicationBuilder.kt:108)
	at EditableCurveSketchKt.main(EditableCurveSketch.kt:23)
	at EditableCurveSketchKt.main(EditableCurveSketch.kt)
Caused by: java.lang.IllegalArgumentException: L end/start overlap Vector2(x=640.3497753421032, y=437.05552212996145) Vector2(x=640.3497753421032, y=437.05552212996145)
	at org.openrndr.shape.Segment.<init>(Shape.kt:43)
	at org.openrndr.shape.ShapeContour.sampleEquidistant(Shape.kt:801)
	at EditableCurve.update(EditableCurve.kt:36)
	at EditableCurve.randomize(EditableCurve.kt:57)
	at EditableCurveSketchKt$main$1$2$3.invoke(EditableCurveSketch.kt:74)
	at EditableCurveSketchKt$main$1$2$4$3$1$1.invoke(EditableCurveSketch.kt:92)
	at EditableCurveSketchKt$main$1$2$4$3$1$1.invoke(EditableCurveSketch.kt)
	at org.openrndr.panel.elements.LayoutBuilderKt$sam$io_reactivex_functions_Consumer$0.accept(LayoutBuilder.kt)
	at io.reactivex.internal.observers.LambdaObserver.onNext(LambdaObserver.java:63)
	... 19 more
io.reactivex.exceptions.OnErrorNotImplementedException: Empty list doesn't contain element at index -1.
	at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:704)
	at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:701)
	at io.reactivex.internal.observers.LambdaObserver.onError(LambdaObserver.java:77)
	at io.reactivex.internal.observers.LambdaObserver.onNext(LambdaObserver.java:67)
	at io.reactivex.subjects.PublishSubject$PublishDisposable.onNext(PublishSubject.java:309)
	at io.reactivex.subjects.PublishSubject.onNext(PublishSubject.java:229)
	at org.openrndr.panel.elements.Slider.setValue(Slider.kt:35)
	at EditableCurveSketchKt$main$1$2$9.invoke(EditableCurveSketch.kt:223)
	at EditableCurveSketchKt$main$1$2$9.invoke(EditableCurveSketch.kt)
	at org.openrndr.events.Event.deliver(Event.kt:112)
	at org.openrndr.internal.gl3.ApplicationGLFWGL3.deliverEvents(ApplicationGLFWGL3.kt:676)
	at org.openrndr.internal.gl3.ApplicationGLFWGL3.drawFrame(ApplicationGLFWGL3.kt:687)
	at org.openrndr.internal.gl3.ApplicationGLFWGL3.loop(ApplicationGLFWGL3.kt:620)
	at org.openrndr.Application$Companion.run(Application.kt:33)
	at org.openrndr.ApplicationKt.application(Application.kt:76)
	at org.openrndr.ApplicationBuilderKt.application(ApplicationBuilder.kt:108)
	at EditableCurveSketchKt.main(EditableCurveSketch.kt:23)
	at EditableCurveSketchKt.main(EditableCurveSketch.kt)
Caused by: java.lang.IndexOutOfBoundsException: Empty list doesn't contain element at index -1.
	at kotlin.collections.EmptyList.get(Collections.kt:35)
	at kotlin.collections.EmptyList.get(Collections.kt:23)
	at org.openrndr.shape.ShapeContour.sub(Shape.kt:880)
	at EditableCurve.addSegmentsTo(EditableCurve.kt:123)
	at EditableCurveSketchKt$main$1$2$2.invoke(EditableCurveSketch.kt:65)
	at EditableCurveSketchKt$main$1$2$4$3$7$1.accept(EditableCurveSketch.kt:148)
	at EditableCurveSketchKt$main$1$2$4$3$7$1.accept(EditableCurveSketch.kt)
	at io.reactivex.internal.observers.LambdaObserver.onNext(LambdaObserver.java:63)
	... 14 more
```

If I don't get the error immediately, I get it later when dragging the end points or the control points.

Is there maybe something wrong in my program that was previously undetected? Or is this something new?

**Comment by hamoid** [comment]
Is this right?

```
        val curve = contour {
            moveTo(Vector2(60.0, 200.0))
            continueTo(Vector2(300.0, 300.0))
            continueTo(Vector2(280.0, 200.0))
            continueTo(Vector2(60.0, 200.0))
            close()
        }
        val curve2 = curve.offset(20.0, SegmentJoin.MITER)

        extend {
            drawer.background(ColorRGBa.WHITE)
            drawer.fill = ColorRGBa.GREEN
            drawer.contour(curve2)
            drawer.fill = ColorRGBa.YELLOW
            drawer.contour(curve)
        }
```
![OPENRNDR-2020-03-19-12 05 11](https://user-images.githubusercontent.com/108264/77061106-0374e180-69da-11ea-876b-21f3e9f6c02e.png)

**Comment by edwinRNDR** [comment]
@hamoid thanks for evaluating this a bit more thoroughly than I have been in the capacity to.

I added constraints to `Segment` to detect problems in the curve pipeline. It turns out that creating quadratic or cubic segments that have control points equal to the start or end point will result in segments that have a zero derivative, which may lead to problems when processing that segment later.

It looks like this happens in `sampleEquidistant`, so we may just have uncovered existing problems. 

_but_

It could also be that a user creates a Segment with co-inciding control/start/end points. They too are faced with a rather harsh exception.

I personally don't think we should place the burden of creating valid curve segments on the user. But that means we need a work-around to calculate segment derivatives in case of co-inciding control points. (I believe they are only 0 at t=0 and t=1, so that shouldn't be super complicated).

That image is definitely not good, it shows a good subdivision scheme is needed in `ShapeContour.offset`.

**Comment by hamoid** [comment]
You're welcome, nice to help :)

Here something else:

```
        var curves = mutableListOf<ShapeContour>()
        curves.add(contour {
            moveTo(Vector2(60.0, 200.0))
            continueTo(Vector2(300.0, 300.0))
            continueTo(Vector2(280.0, 200.0))
            continueTo(Vector2(60.0, 200.0))
            close()
        })
        curves.add(curves[0].offset(20.0, SegmentJoin.MITER))
        curves.add(curves[1].offset(20.0, SegmentJoin.MITER)) // fails

        extend(Screenshots())

        extend {
            drawer.background(ColorRGBa.WHITE)
            curves.forEachIndexed { i, s ->
                drawer.fill = ColorRGBa(0.0, 0.0, 0.0, 0.1)
                drawer.contour(s)
                drawer.fill = null
                drawer.rectangle(s.bounds)
             }
        }
```

This fails to add the third curve with
```
xception in thread "main" java.lang.IllegalArgumentException: use moveTo first
	at org.openrndr.shape.ContourBuilder.lineTo(ShapeBuilder.kt:95)
	at org.openrndr.shape.ShapeContour$offset$joins$2$join$3.invoke(Shape.kt:697)
	at org.openrndr.shape.ShapeContour$offset$joins$2$join$3.invoke(Shape.kt:611)
	at org.openrndr.shape.ShapeBuilderKt.contour(ShapeBuilder.kt:376)
	at org.openrndr.shape.ShapeContour.offset(Shape.kt:694)
	at TestCurveOffsetKt$main$1$2.invoke(TestCurveOffset.kt:30)
	at TestCurveOffsetKt$main$1$2.invoke(TestCurveOffset.kt)
	at org.openrndr.ApplicationBuilder$program$1.setup(ApplicationBuilder.kt:87)
	at org.openrndr.internal.gl3.ApplicationGLFWGL3.loop(ApplicationGLFWGL3.kt:607)
	at org.openrndr.Application$Companion.run(Application.kt:33)
	at org.openrndr.ApplicationKt.application(Application.kt:76)
	at org.openrndr.ApplicationBuilderKt.application(ApplicationBuilder.kt:108)
	at TestCurveOffsetKt.main(TestCurveOffset.kt:12)
	at TestCurveOffsetKt.main(TestCurveOffset.kt)
```

Commenting out that line works fine. So... the copy of the original works, but the copy of the copy doesn't? Not sure what it means :)

**Comment by edwinRNDR** [comment]
ok, _that_ reveals a problem in either the code that creates the miter joins or the (recently added) code that checks for a prior `moveTo` in `lineTo`. Will build proper unit tests for this (as I should have from the start) to root out the problem.

**Comment by edwinRNDR** [comment]
Commit https://github.com/openrndr/openrndr/commit/9f3ea7d6eb0261592857835ad511cfd1c1be0af1 addresses some of the `IllegalArgumentException` cases you reported.

**Comment by hamoid** [comment]
Let me know when it's time to go back to poking those curves ;)

**Comment by edwinRNDR** [comment]
Commit https://github.com/openrndr/openrndr/commit/0680de6fe5023955e3546e2f8a0ff0d751910942 improves the offsetting code. I think now is a good time to test-drive this.

**Comment by edwinRNDR** [comment]
Looks like this is fixed. Thanks for your help @hamoid!
