### ISSUE TITLE
Running the gradle template does not work

### ISSUE THREAD

**Issue by faebser** [openrndr/openrndr#9]
Hi,

I wanted to try out OPENRNDR so I followed the guide at http://guide.openrndr.org/#/Tutorial_Start. I managed to checkout the project and build it, but I am unable to run it.

I get the following error:

```
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
[LWJGL] Failed to load a library. Possible solutions:
	a) Add the directory that contains the shared library to -Djava.library.path or -Dorg.lwjgl.librarypath.
	b) Add the JAR that contains the shared library to the classpath.
[LWJGL] Enable debug mode with -Dorg.lwjgl.util.Debug=true for better diagnostics.
[LWJGL] Enable the SharedLibraryLoader debug mode with -Dorg.lwjgl.util.DebugLoader=true for better diagnostics.
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openrndr.Application$Companion.run(Application.kt:12)
	at org.openrndr.ApplicationKt.application(Application.kt:41)
	at TemplateProgramKt.main(TemplateProgram.kt:23)
Caused by: java.lang.UnsatisfiedLinkError: Failed to locate library: liblwjgl.so
	at org.lwjgl.system.Library.loadSystem(Library.java:147)
	at org.lwjgl.system.Library.loadSystem(Library.java:67)
	at org.lwjgl.system.Library.<clinit>(Library.java:50)
	at org.lwjgl.system.MemoryUtil.<clinit>(MemoryUtil.java:61)
	at org.lwjgl.system.MemoryStack.<init>(MemoryStack.java:61)
	at org.lwjgl.system.MemoryStack.create(MemoryStack.java:82)
	at org.lwjgl.system.MemoryStack.create(MemoryStack.java:71)
	at java.lang.ThreadLocal$SuppliedThreadLocal.initialValue(ThreadLocal.java:284)
	at java.lang.ThreadLocal.setInitialValue(ThreadLocal.java:180)
	at java.lang.ThreadLocal.get(ThreadLocal.java:170)
	at org.lwjgl.system.MemoryStack.stackGet(MemoryStack.java:628)
	at org.lwjgl.system.MemoryStack.stackPush(MemoryStack.java:637)
	at org.lwjgl.system.Callback.<clinit>(Callback.java:40)
	at org.openrndr.internal.gl3.ApplicationGL3.createPrimaryWindow(ApplicationGL3.kt:251)
	at org.openrndr.internal.gl3.ApplicationGL3.<init>(ApplicationGL3.kt:96)
	... 7 more

Process finished with exit code 1
```

**Comment by faebser** [comment]
I'm running Arch Linux
```bash
uname -a
Linux linux-shiny 4.16.13-1-ARCH #1 SMP PREEMPT Thu May 31 23:29:29 UTC 2018 x86_64 GNU/Linux
```

```bash
java -version
openjdk version "1.8.0_172"
OpenJDK Runtime Environment (build 1.8.0_172-b11)
OpenJDK 64-Bit Server VM (build 25.172-b11, mixed mode)
```

**Comment by krksgbr** [comment]
I have just fixed an issue in openrdnr-gradle-template's gradle file that should get rid of this problem.
Can you please pull the change and try again?

**Comment by faebser** [comment]
![screenshot from 2018-06-04 17-39-30](https://user-images.githubusercontent.com/333862/40927154-4da90d18-681e-11e8-98e8-a8fe6f9873fc.png)
Thanks!

**Comment by eccoscreen** [comment]
I'm having this problem on macOS as well. Any ideas how to fix this?

**Comment by eccoscreen** [comment]
Ahh actually I found this in the readme.md
`## On MacOS
add `-XstartOnFirstThread` to JVM arguments (at Run/Edit Configurations/VM Options if you're using IntelliJ Idea)
`

It did the job.

**Comment by ricardomatias** [comment]
I'm going through the guide for the first time on Mac OSX. In the console I see that adding the flag "-XstartOnFirstThread" is being done automatically in case it's not there, but the performance is really bad with a lot of artifacts show (using the `openrndr-template`). After adding it based on the previous comment, the sketch runs smoothly. Maybe it would be worthy to keep in the guide.
